// react/my-app/02_src_配置代理/App.jsx
//创建外壳组件APP
import React, { Component } from "react";
import axios from "axios";

class App extends Component {
    // json-server --watch --port 5000 ./src/students.json
    getStudentData = () => {
        axios.get("http://localhost:3000/students").then(
            (response) => console.log("成功了", response.data),
            (error) => console.log("失败了", error)
        );
    };

    render() {
        return (
            <div>
                <button onClick={this.getStudentData}>
                    点击我获取学生数据
                </button>
            </div>
        );
    }
}

export default App;

// vue/vue-test/16_配置代理/App.vue
<template>
  <div>
    <button @click="getStudents">获取学生信息</button>
    <button @click="getCars">获取汽车信息</button>
  </div>
</template>

<script>
import axios from "axios";
export default {
  name: "App",
  methods: {
    // npm install -g json-server
    // json-server --watch --port 5000 ./src/students.json
    // json-server --watch --port 5001 ./src/cars.json
    getStudents() {
      axios.get("http://localhost:8080/api1/students").then(
        (response) => {
          console.log("请求成功了", response.data);
        },
        (error) => {
          console.log("请求失败了", error.message);
        }
      );
    },
    getCars() {
      axios.get("http://localhost:8080/api2/cars").then(
        (response) => {
          console.log("请求成功了", response.data);
        },
        (error) => {
          console.log("请求失败了", error.message);
        }
      );
    },
  },
};
</script>
